baseURL = "https://sobychacko.github.io/"
languageCode = "en-us"
title = "Soby Chacko"
theme = "charaka"

copyright = "&copy; <a href=\"https://github.com/sobychacko\">Soby Chacko</a> 2019"

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"

[params]

[author]
  name = "Soby Chacko"
  homepage = "https://sobychacko.github.io"

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/sobychacko/"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://www.linkedin.com/in/sobychacko/"
  fa_icon = "fab fa-linkedin-in"

[[params.social]]
  url = "https://twitter.com/sobychacko/"
  fa_icon = "fab fa-twitter"
